name: self-hosted-runner-demo
on:
  push:
    branches:
      - dev
jobs:
    demo-1:
      name: Demo Job 1
      runs-on: ubuntu-latest # pick github-hosted runner with label 'ubuntu-latest'
      steps:
        - name: Display system information
          run: |
            echo "Hostname: $(hostname)"
            echo "OS Version:"
            lsb_release -a || cat /etc/os-release
            echo "Runner Name: ${{ runner.name }}"
            echo "Runner OS: ${{ runner.os }}"
    demo-2:
      name: Demo job 2
      runs-on: [self-hosted, python, X64] # pick up self-hosted runner with the label 'self-hosted', 'python' and 'X64', and it will be AND condition
      steps:
        - name: Display system information
          run: |
            echo "Hostname: $(hostname)"
            echo "OS Version:"
            lsb_release -a || cat /etc/os-release
            echo "Runner Name: ${{ runner.name }}"
            echo "Runner OS: ${{ runner.os }}"